#!/bin/bash

ensure_config() {
  load inquirer

  if [ ! -f $SPUG_SERVICE_CONFIG ]; then
    touch $SPUG_SERVICE_CONFIG
  fi

  load_config_file $SPUG_SERVICE_CONFIG

  if [ -z "$SPUG_SECRET_KEY" ]; then
    inquirer_text "请输入 SECRET KEY:" secret_key "$(curl https://httpbin.zcorky.com/uuid 2>/dev/null | awk -F '"' '{print $4}')"

    export SPUG_SECRET_KEY=$secret_key

    echo "SPUG_SECRET_KEY=$SPUG_SECRET_KEY" >$SPUG_SERVICE_CONFIG
  fi

  # @TODO config should export global in function
  export SPUG_SECRET_KEY=$SPUG_SECRET_KEY
}

export -f ensure_config
